study_name: TPE
trials: 100
seed: 42
metric: val_loss
direction: minimize

sampler:
  name: optuna.samplers.TPESampler

search_space:
  net_config:
    d_model:
      type: categorical
      choices: [32, 64, 128]
    num_layers1:
      type: categorical
      choices: [2, 3, 4, 5]
    modes:
      type: categorical
      choices: [8, 12, 16, 24]
    n_head:
      type: categorical
      choices: [4, 8, 16]
    num_layers2:
      type: categorical
      choices: [2, 3, 4]
    d_ff:
      type: categorical
      choices: [128, 256, 512]
  optimizer_config:
    lr:
      type: float
      min: 1.e-3
      max: 1.e+0
      log: true
  scheduler_config:
    infimum_lr:
      type: float
      min: 1.e-7
      max: 1.e-3
      log: true
